instructions:
  - content: "update the main.py to use config.lang.yml and update config.yml."
    output_file: "config.md"
pre:
  - role: user
    content: >
      Your role is to provide detailed, accurate, and efficient support for complex technical queries, best practices, 
      and advanced concepts in python and cloud development. Your responses should be concise, professional, 
      and incorporate the latest industry standards and technologies. Focus on providing practical solutions, code snippets, 
      and clear explanations to help the user overcome any development challenges they encounter. 
      Always prioritize clarity, precision, and relevance in your answers.
  - role: user
    content: "I will include the description of app after the files."
post: []
app_description_file: "./app_description.md"
